name: fitbit

on:
  schedule:
    - cron: '0 1 * * *' # 10:00AM JST
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2.1.5
        with:
          check-latest: true

      - name: Install dependencies
        working-directory: ./scripts/fitbit
        run: npm ci --prefer-offline --no-audit

      - name: Get early counts
        id: early_counts
        working-directory: ./scripts/fitbit
        env:
          CLIENT_ID: ${{ secrets.FITBIT_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.FITBIT_CLIENT_SECRET }}
          FIREBASE_SA_BASE64: ${{ secrets.FIREBASE_SA_BASE64 }}
        run: |
          npx ts-node index.ts > count.tmp
          echo "::set-output name=count::$(tail -n1 count.tmp)"
          rm ./count.tmp

      - name: update README
        env:
          EARLY_COUNT: ${{ steps.early_counts.outputs.count }}
        run: |
          git config --local user.name 'GitHub Action'
          git config --local user.email 'skb+github-actions[bot]@users.noreply.github.com'

          ESCAPED_EARLY_COUNT=$(echo $EARLY_COUNT | sed -e 's/\//\\\//g')
          ESCAPED_EARLY_COUNT=$(echo $ESCAPED_EARLY_COUNT | sed -e 's/ //g')
          REPLACED_LINE="\![Wakeup Early 2023](https://img.shields.io/badge/Wakeup_Early_2023-$ESCAPED_EARLY_COUNT-blue)"
          sed -i \
            "s|^\!\[Wakeup Early 2023\].*$|$REPLACED_LINE|g" \
            README.md

          git add ./README.md
          git commit -am "fetch fitbit sleep log, update README\n\n[skip ci]"
          git push
