name: fitbit

on:
  schedule:
    - cron: '0 1 * * *' # 10:00AM JST
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2.1.5
        with:
          check-latest: true

      - name: Install dependencies
        working-directory: ./scripts/fitbit
        run: npm ci --prefer-offline --no-audit

      - name: Get early counts
        id: early_counts
        working-directory: ./scripts/fitbit
        env:
          CLIENT_ID: ${{ secrets.FITBIT_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.FITBIT_CLIENT_SECRET }}
          FIREBASE_SA_BASE64: ${{ secrets.FIREBASE_SA_BASE64 }}
        run: |
          npx ts-node index.ts 2023 > count.tmp
          echo "count2023=$(tail -n1 count.tmp)" >> $GITHUB_OUTPUT
          rm ./count.tmp
          npx ts-node index.ts 2024 > count.tmp
          echo "count2024=$(tail -n1 count.tmp)" >> $GITHUB_OUTPUT

      - name: update README
        env:
          EARLY_COUNT_2023: ${{ steps.early_counts.outputs.count2023 }}
          EARLY_COUNT_2024: ${{ steps.early_counts.outputs.count2024 }}
        run: |
          git config --local user.name 'GitHub Action'
          git config --local user.email 'skb+github-actions[bot]@users.noreply.github.com'

          ESCAPED_EARLY_COUNT2023=$(echo $EARLY_COUNT2023 | sed -e 's/\//\\\//g')
          ESCAPED_EARLY_COUNT2023=$(echo $ESCAPED_EARLY_COUNT2023 | sed -e 's/ //g')
          REPLACED_LINE="\![Wakeup Early 2023](https://img.shields.io/badge/Wakeup_Early_2023-$ESCAPED_EARLY_COUNT2023-blue)"
          sed -i \
            "s|^\!\[Wakeup Early 2023\].*$|$REPLACED_LINE|g" \
            README.md

          ESCAPED_EARLY_COUNT2024=$(echo $EARLY_COUNT2024 | sed -e 's/\//\\\//g')
          ESCAPED_EARLY_COUNT2024=$(echo $ESCAPED_EARLY_COUNT2024 | sed -e 's/ //g')
          REPLACED_LINE="\![Wakeup Early 2024](https://img.shields.io/badge/Wakeup_Early_2024-$ESCAPED_EARLY_COUNT2024-blue)"
          sed -i \
            "s|^\!\[Wakeup Early 2024\].*$|$REPLACED_LINE|g" \
            README.md

          git add ./README.md
          git commit -m "fetch fitbit sleep log, update README" -m "[skip ci]"
          git push
