name: fitbit

on:
  schedule:
    - cron: '0 1 * * *' # 10:00AM JST
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup node env
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Ubuntu dependencies
        run: sudo apt-get install -y imagemagick librsvg2-bin

      - name: Install dependencies
        working-directory: ./scripts/fitbit
        run: npm ci --prefer-offline --no-audit

      - name: Get early counts
        id: early_counts
        working-directory: ./scripts/fitbit
        env:
          CLIENT_ID: ${{ secrets.FITBIT_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.FITBIT_CLIENT_SECRET }}
          FIREBASE_SA_BASE64: ${{ secrets.FIREBASE_SA_BASE64 }}
          EARLY_THRESHOLD_HOUR: ${{ secrets.EARLY_THRESHOLD_HOUR }}
          IS_CI: true
        run: |
          git config --local user.name 'GitHub Action'
          git config --local user.email 'skb+github-actions[bot]@users.noreply.github.com'

          npx tsx index.ts 2023
          npx tsx index.ts 2024
          npx tsx index.ts 2025

          convert ./img/sleep-2023.svg ./img/sleep-2023.png
          convert ./img/sleep-2024.svg ./img/sleep-2024.png
          convert ./img/sleep-2025.svg ./img/sleep-2025.png

          git add ./img
          git commit -m "ci: update fitbit data" -m "[skip ci]"
          git push
