name: nirugiri

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: fetch nirugiri view count
        run: |
          python3 -m pip install youtube_dl
          python3 scripts/fetcher.py
      - name: update README
        run: |
          git config --local user.name 'GitHub Action'
          git config --local user.email 'skb+github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -am "fetch nirugiri views count, update README"
          git push
